#pragma once
#include <cstdint>

enum class ErrorCode : uint32_t
{
	UNKNOWN_ERROR = 0,
	FAILED_TIME_FORMAT_CONVERSION,
	FAILED_PROCESS_GET_PID,
	FAILED_PROCESS_GET_FILENAME,
	FAILED_PROCESS_GET_TIMES,
	FAILED_WAIT,
	FAILED_PROCESS_OPEN,
	FAILED_PROCESS_QUERY_INFORMATION,
	FAILED_PROCESS_READ_MEMORY,
	FAILED_LIBRARY_GET_PROC_ADDRESS,
	FAILED_LIBRARY_LOAD,
	FAILED_STRING_CONVERSION,
};
